### ISSUE TITLE
Remove settings for #pll_switcher

### ISSUE THREAD

**Issue by ocean90** [wearerequired/custom-menu-item-types#11]
https://github.com/wearerequired/custom-menu-item-types/blob/eeb0e307a0400a44766bb3f1c8c64ac155a9ac28/classes/Custom_Menu_Items.php#L48-L50

**Comment by grappler** [comment]
What is the reason for this?

**Comment by ocean90** [comment]
Unless I'm missing something, the Language Switcher type is not a custom type provided by this plugin.

**Comment by grappler** [comment]
Ok, that makes sense. It was not clear to me as the issue and the commit only stated what the change is and not why it being done.

In that case we should either continue to have this change in the Prohelvetia Theme or contribute it upstream to Polylang.

**Comment by grappler** [comment]
I have created an issue with Polylang https://github.com/polylang/polylang/issues/307
