### ISSUE TITLE
Allow to select the headline level for headline type 

### ISSUE THREAD

**Issue by ocean90** [wearerequired/custom-menu-item-types#3]
It's currently `h4` by default. https://github.com/wearerequired/custom-menu-item-types/blob/eeb0e307a0400a44766bb3f1c8c64ac155a9ac28/classes/Custom_Menu_Items.php#L86

**Comment by grappler** [comment]
I think we should add a headline level option to the other menu items too that have a header. See #16

**Comment by grappler** [comment]
I feel that the heading dropdown should come before the custom class field.
![image](https://user-images.githubusercontent.com/1785641/47225312-138c2a00-d3be-11e8-8e53-484df0e4bf24.png)
