### ISSUE TITLE
Rename wp_nav_menu_item_fields filter to clarify it's not from core

### ISSUE THREAD

**Issue by ocean90** [wearerequired/custom-menu-item-types#9]
Related: #2.

**Comment by grappler** [comment]
After seeing the code changes I am not sure this is best. We are not changing a lot of things in our custom class that the core filter `wp_nav_menu_item_fields` should not work.

If another plugin was using `wp_nav_menu_item_fields` then they would only modify the core menu items and not our custom menu types.

**Comment by ocean90** [comment]
@grappler There is no such filter in core. The custom class only exists because of this custom filter.
